server:
  ssl:
    key-store: video-class/videoclass.p12
    key-store-password: 123456
    key-store-type: PKCS12
    key-alias: videoclass
  port: 8443

spring:
  thymeleaf:
    mode: HTML5
    cache: false
  h2:
    console:
      enabled: true
      settings:
        trace: true
      path: /h2-console
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test
  devtools:
    livereload:
      enabled: true